id,problem_letter,problem_name,problem_id,user_id,send_time,state,description,program,score,lang
22,A,Neon,2,2,2023-09-24 18:47:50.208808,Тестируется,,sq,100,2
18,C,Neon,2,2,2023-09-21 15:00:15.473756,Тестируется,,python,90,2
25,A,Neon,2,2,2023-09-24 18:51:36.057261,Тестируется,,sq,,2
26,A,Neon,2,2,2023-10-15 13:13:31.559252,Тестируется,,"import time

time.sleep(5000)",,1
28,A,Neon,2,2,2023-10-18 18:27:19.409318,Тестируется,,"print(""478"")",,1
19,C,Neon,2,2,2023-09-21 15:01:00.288296,Тестируется,,python,50,2
21,C,Neon,2,2,2023-09-21 15:01:53.896737,Тестируется,,python,5,2
30,B,Футбол,5,2,2023-10-26 13:08:40.708081,Тестируется,"[
  {
    ""success"": false,
    ""out"": ""Traceback (most recent call last):\n  File \""/adir\\4/main.py\"", line 1, in <module>\n    xxxx\nNameError: name 'xxxx' is not defined"",
    ""msg"": ""RUNTIME_ERROR"",
    ""time"": 22
  },
  {
    ""success"": false,
    ""out"": ""Traceback (most recent call last):\n  File \""/adir\\5/main.py\"", line 1, in <module>\n    xxxx\nNameError: name 'xxxx' is not defined"",
    ""msg"": ""RUNTIME_ERROR"",
    ""time"": 12
  },
  {
    ""success"": false,
    ""out"": ""Traceback (most recent call last):\n  File \""/adir\\6/main.py\"", line 1, in <module>\n    xxxx\nNameError: name 'xxxx' is not defined"",
    ""msg"": ""RUNTIME_ERROR"",
    ""time"": 10
  }
]",sq,,1
2,B,Neon,2,1,2023-09-24 18:51:05.416562,Протестировано,"[
  {
    ""success"": false,
    ""out"": ""Main.java:1: error: reached end of file while parsing\nsq\n^\n1 error\nerror: compilation failed"",
    ""msg"": ""RUNTIME_ERROR"",
    ""time"": 326
  },
  {
    ""success"": false,
    ""out"": ""Main.java:1: error: reached end of file while parsing\nsq\n^\n1 error\nerror: compilation failed"",
    ""msg"": ""RUNTIME_ERROR"",
    ""time"": 287
  }
]",sq,0,2
31,B,Футбол,5,2,2023-11-10 17:02:11.970514,Протестировано,"[
  {
    ""success"": false,
    ""out"": ""Traceback (most recent call last):\n  File \""/adir\\4/main.py\"", line 1, in <module>\n    xxxx\nNameError: name 'xxxx' is not defined"",
    ""msg"": ""RUNTIME_ERROR"",
    ""time"": 22
  },
  {
    ""success"": false,
    ""out"": ""Traceback (most recent call last):\n  File \""/adir\\5/main.py\"", line 1, in <module>\n    xxxx\nNameError: name 'xxxx' is not defined"",
    ""msg"": ""RUNTIME_ERROR"",
    ""time"": 12
  },
  {
    ""success"": false,
    ""out"": ""Traceback (most recent call last):\n  File \""/adir\\6/main.py\"", line 1, in <module>\n    xxxx\nNameError: name 'xxxx' is not defined"",
    ""msg"": ""RUNTIME_ERROR"",
    ""time"": 10
  }
]",05,100,1
17,C,Neon,2,4,2023-09-21 14:59:32.451938,Тестируется,,python,0,2
20,C,Neon,2,4,2023-09-21 15:01:27.323250,Тестируется,,python,80,2
23,A,Neon,2,3,2023-09-24 18:50:03.296020,Тестируется,,sq,,2
27,A,Neon,2,3,2023-10-15 13:13:33.810387,Тестируется,,"import time

time.sleep(5000)",,1
29,A,Neon,2,4,2023-10-26 13:07:50.535370,Тестируется,,x = 0,,1
